/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as AdminImport } from './routes/_admin'
import { Route as AdminIndexImport } from './routes/_admin/index'
import { Route as AuthSignInImport } from './routes/_auth/sign-in'
import { Route as AdminCreateAccountImport } from './routes/_admin/create-account'
import { Route as AdminLayoutImport } from './routes/_admin/_layout'
import { Route as AdminLayoutUsersImport } from './routes/_admin/_layout/users'
import { Route as AdminLayoutAnalyticsImport } from './routes/_admin/_layout/analytics'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/_admin',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)

const AdminCreateAccountRoute = AdminCreateAccountImport.update({
  path: '/create-account',
  getParentRoute: () => AdminRoute,
} as any)

const AdminLayoutRoute = AdminLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => AdminRoute,
} as any)

const AdminLayoutUsersRoute = AdminLayoutUsersImport.update({
  path: '/users',
  getParentRoute: () => AdminLayoutRoute,
} as any)

const AdminLayoutAnalyticsRoute = AdminLayoutAnalyticsImport.update({
  path: '/analytics',
  getParentRoute: () => AdminLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/_admin/_layout': {
      preLoaderRoute: typeof AdminLayoutImport
      parentRoute: typeof AdminImport
    }
    '/_admin/create-account': {
      preLoaderRoute: typeof AdminCreateAccountImport
      parentRoute: typeof AdminImport
    }
    '/_auth/sign-in': {
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof AuthImport
    }
    '/_admin/': {
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/_admin/_layout/analytics': {
      preLoaderRoute: typeof AdminLayoutAnalyticsImport
      parentRoute: typeof AdminLayoutImport
    }
    '/_admin/_layout/users': {
      preLoaderRoute: typeof AdminLayoutUsersImport
      parentRoute: typeof AdminLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AdminRoute.addChildren([
    AdminLayoutRoute.addChildren([
      AdminLayoutAnalyticsRoute,
      AdminLayoutUsersRoute,
    ]),
    AdminCreateAccountRoute,
    AdminIndexRoute,
  ]),
  AuthRoute.addChildren([AuthSignInRoute]),
])

/* prettier-ignore-end */
